// autogenerated by genswiftstrings.swift

import Foundation

enum Strings: String
{
	case setFenceRadiusInstructions
	case showGeoFenceButton
	case preBuildProcessingButton
	case pinchForRadiusHelp
	case pickContentHelp
	case showTooltipButton
	case ibDesignableButton
	case tapToSetRadius
	case stringLocalizationButton
	case mapAnnotationTitle
}
